services:
  patefon:
    container_name: patefon
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      postgres:
        condition: service_started
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/uploads
  
  postgres:
    container_name: postgres
    image: postgres:15.0
    environment:
      POSTGRES_DB: patefon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5450:5432"
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d

  redis:
    container_name: redis
    image: redis:7.4.1
    ports:
      - "6380:6379"