services:
  patefon:
    container_name: patefon
    build:
      context: .
      dockerfile: main_app/Dockerfile
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
      auth:
        condition: service_started
    restart: always
    ports:
      - "8082:8082"
      - "8080:8080"
    volumes:
      - ./uploads:/uploads

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    depends_on:
      postgres:
        condition: service_started
    restart: always
    ports:
      - "8081:8081"

  websocket:
    container_name: websocket
    build:
      context: .
      dockerfile: websocket_service/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_started
      patefon:
        condition: service_started
    restart: always
    ports:
      - "8083:8083"

  surveys:
    container_name: surveys
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    depends_on:
      survey_db:
        condition: service_started
    restart: always
    ports:
      - "8084:8084"

  postgres:
    container_name: postgres
    image: postgres:15.0
    environment:
      POSTGRES_DB: patefon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5450:5432"
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d

  surveys_db:
    container_name: surveys_db
    image: postgres:15.0
    environment:
      POSTGRES_DB: surveys
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5451:5433"
    volumes:
      - ./db/survey_migrations:/docker-entrypoint-initdb.d


  rabbitmq:
   image: rabbitmq:3.10.7-management
   hostname: rabbitmq
   restart: always
   environment:
     - RABBITMQ_DEFAULT_USER=root
     - RABBITMQ_DEFAULT_PASS=root
   ports:
     - 15672:15672
     - 5672:5672 