services:
  patefon:
    container_name: patefon
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/uploads
  
  postgres:
    container_name: postgres
    image: postgres:15.0
    environment:
      POSTGRES_DB: patefon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5450:5432"
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d


  rabbitmq:
   image: rabbitmq:3.10.7-management
   hostname: rabbitmq
   restart: always
   environment:
     - RABBITMQ_DEFAULT_USER=root
     - RABBITMQ_DEFAULT_PASS=root
   ports:
     - 15672:15672
     - 5672:5672 